# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=60)),
                ('f_name', models.CharField(max_length=60)),
                ('l_name', models.CharField(max_length=60)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
