# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
