# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190316_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emplee_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='employees/'),
            preserve_default=False,
        ),
    ]
