# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-16 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_emplee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emplee_image',
            new_name='employee_image',
        ),
    ]
