# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190316_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
