# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_employee_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('ICT', 'ICT'), ('Finance', 'Finance'), ('Admin', 'Admin')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
